# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johan Stenberg's Blog
email: johanstenberg92@gmail.com
description: Personal blog of Johan Stenberg, I try to focus solidly on technical content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johanstenberg92.github.io" # the base hostname & protocol for your site
github_username:  johanstenberg92

# Build settings
markdown: kramdown
